package org.fpsrobotics.actuators;

public enum EAugerPresets
{
//	LOW_BAR, TOP_LIMIT, FOURTY_KAI, SHOOT_HIGH, INTAKE, SHOOT_LOW, STANDARD_DEFENSE;
	LOW_BAR, TOP_LIMIT, FOURTY_KAI, INTAKE, STANDARD_DEFENSE_AUGER, FOURTY_KAI_END_GAME;
}
