package org.fpsrobotics.actuators;

public enum EAugerPresets
{
	LOW_BAR, TOP_LIMIT, FOURTY_KAI, INTAKE, STANDARD_DEFENSE_AUGER, FOURTY_KAI_AUTO;
//	LOW_BAR, TOP_LIMIT, FOURTY_KAI, INTAKE, STANDARD_DEFENSE_AUGER, END_GAME, PORTCULLIS, FOURTY_KAI_AUTO;
}
