package org.fpsrobotics.actuators;

public enum EShooterPresets
{
	INTAKE, LOW_BAR, STANDARD_DEFENSE_SHOOTER, SHOOTER_POSITION_AT_DEFENSE_TWO_AUTO, SHOOTER_POSITION_AT_DEFENSE_THREE_AUTO, SHOOTER_POSITION_AT_DEFENSE_FOUR_AUTO, SHOOTER_POSITION_AT_DEFENSE_FIVE_AUTO, CENTER_SHOT_TELEOP, CORNER_SHOT_TELEOP, LOW_BAR_SHOOT_HIGH_AUTO;
}
