package org.fpsrobotics.actuators;

public enum EShooterPresets
{
//	INTAKE, LOW_BAR, STANDARD_DEFENSE_SHOOTER, STANDARD_DEFENSE_SHOOTER_AUTO, SHOOTER_POSITION_AT_DEFENSE_FIVE;
	INTAKE, LOW_BAR, STANDARD_DEFENSE_SHOOTER, SHOOTER_POSITION_AT_DEFENSE_TWO, SHOOTER_POSITION_AT_DEFENSE_FIVE;
}
